# Generated by Django 3.2.8 on 2021-10-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numContrat', models.IntegerField(unique=True, verbose_name='Numéro Contrat')),
                ('type_assurance', models.IntegerField(choices=[(1, 'Automobile'), (2, 'Incendie & Risques'), (3, 'Vie'), (4, 'Santé'), (5, 'Transport')])),
                ('cin_client', models.IntegerField(unique=True, verbose_name='Cin du client')),
                ('date_contract', models.DateField(auto_now_add=True, verbose_name='Date du contrat')),
                ('serie_voiture', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Serie Voiture')),
                ('statut_contrat', models.CharField(default='En cours du traitement', max_length=255, verbose_name='Statut du contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cin', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('num_tel', models.IntegerField()),
                ('type_devis', models.IntegerField(choices=[(1, 'Automobile'), (2, 'Incendie & Risques'), (3, 'Vie'), (4, 'Santé'), (5, 'Transport')])),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
